### ISSUE TITLE
Image not showing up

### ISSUE THREAD

**Issue by gomigg07** [shaanaliyev/r-place-overlay#1]
I have set everything up correctly. I set the position to 100,100 just to test how the offsetting works and what math I need to do. I haved looked at the center, top left and bottom left corner of the canvas, and the image does not show up. Maybe there is a problem with either my link or my image? (My image is at 1:1 pixel scale. I don;t know how I'm supposed to resize it)

https://new.reddit.com/r/place/?jsontemplate=https%3A%2F%2Frentry.co%2Ftd9zx%2Fraw&screenmode=fullscreen

PS: how much do i need to add/subtract from the coordinates to input them correctly into the script?

**Comment by Ritiwj04** [comment]
hey did you manage to get it done 
cause I am running into the same problem and would really really appreciate some help

**Comment by sh2aliyev** [comment]
@Ritiwj04 Please check the issue https://github.com/shaanaliyev/r-place-overlay/issues/2
