### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by Ritiwj04** [shaanaliyev/r-place-overlay#2]
I have Followed all the steps correctly it worked intially with a image that was the wrong size bu then it just stopped working 
I would really appreciate some suggestions on how it might work 
thankyou

**Comment by sh2aliyev** [comment]
Checklist: 

1. Can you see the icon?
![image](https://github.com/shaanaliyev/r-place-overlay/assets/35802638/eba4fd1a-c6c3-420c-896c-4bb6aaf883e0)
If not, please try turning the script off and on:
![image](https://github.com/shaanaliyev/r-place-overlay/assets/35802638/b6b00595-cf42-4634-8151-cce48a6aaccf)
and then reload the page.

2. To check if your template is working, set `x` and `y` to 0 and go to the top-left of the canvas. Can see the overlay there?
    - No: there is something wrong with your template. Please check the guide again.
    - Yes: everything is alright. You just need to correct your coordinates.
       > To move right, add to `x`; to move down, add to `y`.

> **Note**: The image you are using when creating the template should be pixel-perfect sized with the canvas. This means, for example, you cannot use a 1600x1200 image to fit a 25x10 space.
