### ISSUE TITLE
template pixels not appearing on screen

### ISSUE THREAD

**Issue by SunSlice** [shaanaliyev/r-place-overlay#6]
Hello, I've followed the guide as well as I could, the setting "show contact info besides templates" checked shows where I would want my templates to preview, but they don't. The info does but the pixel template does not, and I don't know why. The templates are not hidden either. Realoading the browser doesn't fix this. Reinstalling the main script doesn't fix it either.

the rentry: [https://rentry.co/5ddau/raw](https://rentry.co/5ddau/raw)
images: [https://i.imgur.com/K3eAHKA.png](https://i.imgur.com/K3eAHKA.png) & [https://i.imgur.com/azjCcY9.png](https://i.imgur.com/azjCcY9.png)

what's visible on my screen: [https://cdn.discordapp.com/attachments/1082686708656656454/1133052440246227084/image.png](https://cdn.discordapp.com/attachments/1082686708656656454/1133052440246227084/image.png)

other templates work perfectly fine

**Comment by SunSlice** [comment]
I missed brackets ["URL_HERE"] for the images... my bad I guess

**Comment by sh2aliyev** [comment]
Hi, please avoid editing the main syntax; the image sources should be wrapped in `[ `and `]` (the script expects array, not string).

The rentry should be like this: https://rentry.co/dxv5c/raw
